//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3512.0
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3512.0.
// 
namespace TemperatureClient.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TemperatureServerSoap", Namespace="http://www.deitel.com/csphtp1/ch21/")]
    public class TemperatureServer : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public TemperatureServer() {
            this.Url = "http://localhost/TemperatureServer/TemperatureServer.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.deitel.com/csphtp1/ch21/UpdateWeatherConditions", RequestNamespace="http://www.deitel.com/csphtp1/ch21/", ResponseNamespace="http://www.deitel.com/csphtp1/ch21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateWeatherConditions() {
            this.Invoke("UpdateWeatherConditions", new object[0]);
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginUpdateWeatherConditions(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("UpdateWeatherConditions", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public void EndUpdateWeatherConditions(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.deitel.com/csphtp1/ch21/Cities", RequestNamespace="http://www.deitel.com/csphtp1/ch21/", ResponseNamespace="http://www.deitel.com/csphtp1/ch21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Cities() {
            object[] results = this.Invoke("Cities", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCities(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Cities", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndCities(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.deitel.com/csphtp1/ch21/Descriptions", RequestNamespace="http://www.deitel.com/csphtp1/ch21/", ResponseNamespace="http://www.deitel.com/csphtp1/ch21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Descriptions() {
            object[] results = this.Invoke("Descriptions", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginDescriptions(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Descriptions", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndDescriptions(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.deitel.com/csphtp1/ch21/Temperatures", RequestNamespace="http://www.deitel.com/csphtp1/ch21/", ResponseNamespace="http://www.deitel.com/csphtp1/ch21/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] Temperatures() {
            object[] results = this.Invoke("Temperatures", new object[0]);
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginTemperatures(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Temperatures", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public string[] EndTemperatures(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string[])(results[0]));
        }
    }
}
