//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.0.3328.4
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.0.3328.4.
// 
namespace EquationGeneratorClient.localhost {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GeneratorSoap", Namespace="http://www.deitel.com/csphtp1/ch21")]
    public class Generator : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public Generator() {
            this.Url = "http://localhost/EquationGenerator/Generator.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.deitel.com/csphtp1/ch21/GenerateEquation", RequestNamespace="http://www.deitel.com/csphtp1/ch21", ResponseNamespace="http://www.deitel.com/csphtp1/ch21", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Equation GenerateEquation(string operation, int level) {
            object[] results = this.Invoke("GenerateEquation", new object[] {
                        operation,
                        level});
            return ((Equation)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginGenerateEquation(string operation, int level, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("GenerateEquation", new object[] {
                        operation,
                        level}, callback, asyncState);
        }
        
        /// <remarks/>
        public Equation EndGenerateEquation(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((Equation)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.deitel.com/csphtp1/ch21")]
    public class Equation {
        
        /// <remarks/>
        public string LeftHandSide;
        
        /// <remarks/>
        public string RightHandSide;
        
        /// <remarks/>
        public int Left;
        
        /// <remarks/>
        public int Right;
        
        /// <remarks/>
        public int Result;
        
        /// <remarks/>
        public string Operation;
    }
}
